### ISSUE TITLE
Error given when copied and pasted MIXAL from txt file.

### ISSUE THREAD

**Issue by akenner712** [linnando/MIXEmulator#16]
Typed out Program P and ran it successfully. Copied, pasted and saved Program P in a txt file. Copied and pasted from txt file, and getting error "Invalid expression 500."
[MIXAL-First500PrimesToLinePrinter.txt](https://github.com/linnando/MIXEmulator/files/10876267/MIXAL-First500PrimesToLinePrinter.txt)

**Comment by linnando** [comment]
Looks like the problem is in mismatching newline characters. I have applied a quickfix but am not sure it works in all cases. Could you please check it works for your setup?
